sudo:
  false

language:
  node_js

node_js:
  - 6

script:
  - npm run test

after_script:
  - npm run coveralls

deploy:
  provider: npm
  email: eskarev@gmail.com
  skip_cleanup: true
  on:
    tags: true
    branch: master
  api_key:
    secure: Te6s0RvDTz4mwU7yHRt4gcha8PFNIqYdkOQ6Tp20uxJmPoqJgEgKAli2Sq/0r8SAvdxH6GMvOmzdnrIQ6h5T8vGOWlp4qEO8Opvk4Gg7yEW1qcYNF+Butka+CaDlBaSEEE/sra37xVEJQUOoYQjSxsz9wAQhBygz8i2RufNQUsMbUO2eeLB5BALKlvMwhwtaL/oRA/82AlURp5tjNDF91PIdPG4uuY4fAplTa9Chlnq1tDDmlNMxg378RU9AnjBMpQ91hQaYbrx98OLNG2ULBD8jRT4FDnVhibHRZG9Nwbjv63uaw4gxWa8IIUj1qsMYM6QPEIx2GM+YskmhFUBUjkUOt8a/2Sf2kZB6bXTDNBh8bU9e2gKCPciCGQGDC0yomAzmC+I3uruC7yJEXpXOx2pvzS59PNU6lEdOM7ahvnj1cZN9XBw2j2D6cST344e42I/wEtnSx/aInVDonKKljSjIEyXq9Qfm7/wUQzNpcFRF3MgEBtbNmVFhehqDN+WIBv4LYztI5nV1ns+UotpZahgxDXGGB8B4ub5CTGcdpYUyCbHuTwT5vtarme+qOOmbYIVj3QSYjLE9rpLOGxKflJ5nwSEE5QAk02dhRWnYlzvQNh7Qrt2/qBjQBCfw7AdXqRtttaRKlmuhvJC7+qVopgqfGkfQIhHHIKjJ0qkyH5E=
