sudo:
  false

language:
  node_js

node_js:
  - 4
  - 6

script:
  - npm test
  - npm run review

after_script:
  - "node_modules/.bin/babel-node node_modules/.bin/babel-istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
